import './globals.css'
import Link from "next/link";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html>
	  		<body>
					<h1><Link href="/">WEB</Link></h1>
			  <ol>
				  <li><Link href="/read/1">html</Link></li>
				  <li><Link href="/read/2">css</Link></li>
				  {children}
			  </ol>
	  		</body>
		</html>
	)
}
